import React from 'react';
import { connect } from 'react-redux';
import moment from 'moment';
import firebase, { Promise } from 'firebase';
import { push } from 'react-router-redux';
import { resetNext } from '../../actions/auth';
var randtoken = require('rand-token');

/*This is the dashboard component which simply shows the usage statistics
when the user logs in*/

class Dashboard extends React.Component {


	/*This function calculates the total number of tests the clinician has completed by retrieving
	the total number of TUG, PEQ, and L tests for a user. This value is displayed in the Usage
	Statistics.*/
	calculateTotalTests() {
		const userId = firebase.auth().currentUser.uid;
		var ref = firebase.database().ref("/sessions/" + userId.toString());
		ref.once("value")
			.then(function(snapshot) {
				snapshot.forEach(function(childSnapshot) {
					var key = childSnapshot.key;
					var tugNumber = childSnapshot.child("tests").child("TUG TEST").numChildren();
					var peqNumber = childSnapshot.child("tests").child("PEQ TEST").numChildren();
					var lNumber = childSnapshot.child("tests").child("L TEST").numChildren();
					var sum = tugNumber + peqNumber + lNumber;
					document.getElementById("total").innerHTML = Math.ceil(sum);

				})
		})
	}

	/*This function calculates the average number of tests completed by all clinicians which is done
	 by retrieving the total number of TUG, PEQ, and L tests for all users and dividing it by the number
	 of all users. This value is displayed in the Usage Statistics.*/
	calculateAverageTests() {

		var ref = firebase.database().ref("/sessions/");
		ref.once("value")
			.then(function(snapshot) {
				snapshot.forEach(function(childSnapshot) {
					childSnapshot.forEach(function(formSnapshot) {

						var key = formSnapshot.key;
						var numUsers = childSnapshot.numChildren();
						var tugNumber = formSnapshot.child("tests").child("TUG TEST").numChildren();
						var peqNumber = formSnapshot.child("tests").child("PEQ TEST").numChildren();
						var lNumber = formSnapshot.child("tests").child("L TEST").numChildren();
						var sum = tugNumber + peqNumber + lNumber;
						document.getElementById("average").innerHTML = sum/numUsers;


					})
				})
		})
	}



	/*This is where the component is rendered.*/
	render() {

		return (
      <div id="wrapper" className="container">
			{/*calculateTotalTests and calculateAverageTests are executed to display the test values
				under usage statistics.*/}
			{this.calculateTotalTests()}
			{this.calculateAverageTests()}
        <div className="dashWidth">
          <div className="panel panel-default col-lg panel-info">
            <div className="panel-heading text-center"><h3 className = "dash">Dashboard</h3></div>
              <h3 className="text-center">Usage Statistics</h3>
              <div className="panel-body text-left">
              <div className="row">
                <div className="col-sm-6">
                  <div className="card statCard">
                    <div className="card-block">
                      <h3 className="card-title text-center">Number of reports generated this month</h3>
                      <br />
                      <br />
                      <br />
                      <br />
                      <div className = "pull-center"><p className="card-text text-center"><h3 id = "total" className = "total">0</h3></p></div>
                      <br />
                      <br />
                      <br />
                      <br />
                    </div>
                  </div>
                </div>
                <div className="col-sm-6">
                  <div className="card statCard">
                    <div className="card-block">
                      <h3 className="card-title text-center">Average number of reports generated by clinicians this month</h3>
                      <br />
                      <br />
                      <br />
                      <br />
                      <div className = "pull-center"><p className="card-text text-center"><h3 id = "average" className = "average">0</h3></p></div>
                      <br />
                      <br />
                      <br />
                      <br />
                    </div>
                  </div>
                </div>
              </div>

              </div>
          </div>
        </div>
      </div>
		)
	}
}

export default Dashboard;
